### ISSUE TITLE
Update possible choices once a filter is selected

### ISSUE THREAD

**Issue by skhillon** [skhillon/ShinyVisaExploration#10]
Ex) If "Apple" is selected for Employer, there should not be any construction worker option under Job Title or SOC name, etc.

**Comment by jmoren48** [comment]
The filters work! Thank god for Christina when you select something that doesn't exist i.e. "Apple" and "Construction Worker" the map returns blank which is what we want.

**Comment by cewalden** [comment]
The majority of this is done, we still need to narrow down the jobs that aren't offered by that employer
