### ISSUE TITLE
Report Notebook

### ISSUE THREAD

**Issue by skhillon** [skhillon/ShinyVisaExploration#4]
## From Rubric
____/3 Introduction to the project (Report)
____/3 Explanation of the statistical concepts (Report)
____/3 Appropriately divided into sections (Report)
____/3 Produces plots to illustrate results (Report)
____/3 Plots are adjusted to publication quality (Report)
____/3 Explains results (Report)
____/3 Provides an overall conclusion (Report)
____/6 Overall quality (organization, grammar, explanation, etc.) (Report)

**Comment by jmoren48** [comment]
finally finished!!
